#+TITLE: In-class assignment: Subsetting and Extracting
#+AUTHOR: [YourName] 
#+SUBTITLE: Introduction to data science (DSC 105) Fall 2022
#+STARTUP: overview hideblocks indent
#+PROPERTY: header-args:R :session *R* :results output
* README

- Practice file for the lecture on "Subsetting and extracting indices
  in R" ([[https://github.com/birkenkrahe/ds1/blob/piHome/org/6_subsetting.org][GitHub]])
- All content from that lecture is also available [[https://www.youtube.com/playlist?list=PL6SfZh1-kWXl3_YDc-8SS5EuG4h1aILHz][on YouTube]]
- Create, execute and debug R code blocks as needed
- Emacs + ESS + Org-mode and R must be installed
- Upload the completed file as a class assignment ([[https://lyon.instructure.com/courses/568/assignments/2952][Canvas]])
- You find the solutions in the PDF repository (GitHub)

* TODO IDENTIFY YOURSELF

  - Update the ~#+AUTHOR:~ information in the header
  - Add ~(pledged)~ after your name
  - Put your cursor on the headline of this section, and type ~S <LEFT>~
    until you see ~DONE~ instead of ~TODO~ next to the title.
  - Perform this last step each time you complete a section.

* TODO 10 QUESTIONS ABOUT THE NILE

1) Print the length of the data set ~Nile~ using an R function.

2) Retrieve the second to fifth value of the ~Nile~ data set.

3) Which data science (not R) question does the last output answer?
   Write a full sentence.

   #+begin_quote
     ...
   #+end_quote

4) Extract the year that corresponds to the last value of
   ~Nile~. Remember that the years are stored in ~time(Nile)~.
   
5) What was the Nile flow in 1967? Tip: use a logical operator, and
   store ~time(Nile)~ in ~t~ for the remaining questions.
   
6) What is the index of the third-to-last element of ~Nile~? Use the
   ~which~ function to answer this question.

7) How many values of ~Nile~ are larger than the third-to-last value?

8) How much water flowed down the Nile between 1871 and 1970?

9) In which year was the Nile at its lowest level? Use the ~min~
   function for this task and store the result in ~tmin~

10) Make a line plot of all observations in the data set ~Nile~ using
    ~plot~, mark the year of the lowest level of the Nile with a
    vertical line, and the average flow through the Nile with a
    horizontal line. The result is stored in ~nile.png~.

    You can draw a vertical line at point ~x~ with ~abline(v=x)~, and a
    horizontal line at point ~y~ with ~abline(h=y)~.

    #+begin_src R :results graphics file :file nile.png
      ...
    #+end_src

    Tip: You can change the appearance of lines with the parameters ~col~,
    ~lty~, ~lwd~. E.g. ~col="red, lty=2, lwd=2~ for a red, dashed, thick
    line.
